# config.py

# List of actions
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']

# Other hyperparameters
EPSILON_START = 1.0
EPSILON_END = 0.05
EPSILON_DECAY = 100_000
GAMMA = 0.995
LEARNING_RATE = 3e-4
TARGET_UPDATE = 100
BATCH_SIZE = 64
TRANSITION_HISTORY_SIZE = 100_000
