# config.py

# List of actions
ACTIONS = ['UP', 'RIGHT', 'DOWN', 'LEFT', 'WAIT', 'BOMB']

# Other hyperparameters
GAMMA = 0.995
LEARNING_RATE = 3e-4
TARGET_UPDATE = 100
BATCH_SIZE = 64
TRANSITION_HISTORY_SIZE = 100_000

# Softmax parameters
TEMPERATURE_START = 10
TEMPERATURE_END = 0.01
TEMPERATURE_DECAY = 100_000